Turkish translation
sthewissen/MVP pull request #56
Opened 2020-12-27 15:44 UTC by cihanyakar

Turkish translation has been added.

2020-12-27 15:45 UTC, cihanyakar commented
#23

2020-12-29 10:40 UTC, sthewissen commented
Awesome! Could I trouble you for 3 more texts that I forgot? 

"Sign in"
"Swipe to continue"
"Try with a demo account"

Feel free to leave the translations here and I'll make sure they make their way in :)

2020-12-29 12:15 UTC, cihanyakar commented
Sure, I'll have added tomorrow at the latest.

2020-12-29 12:32 UTC, sthewissen commented on MVP/Resources/Translations.tr.resx
> +    <value>Sign in</value>
@cihanyakar I already added the 3 English versions of the labels here for you :)

2020-12-29 12:39 UTC, cihanyakar commented on MVP/Resources/Translations.tr.resx
> +    <value>Sign in</value>
```suggestion
    <value>Oturum Aç</value>
```

2020-12-29 12:39 UTC, cihanyakar commented on MVP/Resources/Translations.tr.resx
> +    <value>Swipe to continue</value>
```suggestion
    <value>Devam etmek için kaydırın</value>
```

2020-12-29 12:40 UTC, cihanyakar commented on MVP/Resources/Translations.tr.resx
> +    <value>Try with a demo account</value>
```suggestion
    <value>Bir demo hesap ile deneyin</value>
```

2020-12-29 12:42 UTC, cihanyakar reviewed
I think it is OK now

2020-12-29 12:55 UTC, sthewissen approved these changes

2020-12-29 12:55 UTC, sthewissen commented
Awesome! I also had someone else respond that he wanted to do Turkish, so I asked him to review this PR. That way at least 2 people have looked at it and we can merge this once the review is done 👍

Thanks for the effort so far!

2020-12-29 17:06 UTC, polatpinar requested changes
Looks good

2020-12-29 17:06 UTC, polatpinar commented on MVP/Resources/Translations.tr.resx
> +    <value>Getting URL metadata...</value>
Maybe "URL meta verisi alınıyor"?

2020-12-29 20:52 UTC, polatpinar approved these changes

2020-12-29 21:08 UTC, merged